package cosmos.multiple.model;

public class MultipleChoice {
	private String MULTIPLECHOICEID;
	private String MULTIPLECHOICEONE;
	private String MULTIPLECHOICETWO;
	private String MULTIPLECHOICETHREE;
	private String MULTIPLECHOICEFOUR;
	
	
	public String getMULTIPLECHOICEID() {
		return MULTIPLECHOICEID;
	}
	public void setMULTIPLECHOICEID(String mULTIPLECHOICEID) {
		MULTIPLECHOICEID = mULTIPLECHOICEID;
	}
	public String getMULTIPLECHOICEONE() {
		return MULTIPLECHOICEONE;
	}
	public void setMULTIPLECHOICEONE(String mULTIPLECHOICEONE) {
		MULTIPLECHOICEONE = mULTIPLECHOICEONE;
	}
	public String getMULTIPLECHOICETWO() {
		return MULTIPLECHOICETWO;
	}
	public void setMULTIPLECHOICETWO(String mULTIPLECHOICETWO) {
		MULTIPLECHOICETWO = mULTIPLECHOICETWO;
	}
	public String getMULTIPLECHOICETHREE() {
		return MULTIPLECHOICETHREE;
	}
	public void setMULTIPLECHOICETHREE(String mULTIPLECHOICETHREE) {
		MULTIPLECHOICETHREE = mULTIPLECHOICETHREE;
	}
	public String getMULTIPLECHOICEFOUR() {
		return MULTIPLECHOICEFOUR;
	}
	public void setMULTIPLECHOICEFOUR(String mULTIPLECHOICEFOUR) {
		MULTIPLECHOICEFOUR = mULTIPLECHOICEFOUR;
	}
	
	
}
